import type { Metadata } from "next";
import "./globals.css";
// 認証プロバイダーを追加
import { Providers } from "@/app/(workspace)/providers"
import { Navigation } from "@/app/components/Navigation"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body>
        <Providers>
          <Navigation/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
